import { Router } from "express";
import { requireAuth } from "../middleware/requireAuth.js";
import { addNewAccount, fetchAccounts, } from "../controllers/trading/accounts.controller.js";
import { addNewTrade, closeTrade, fetchTrades, } from "../controllers/trading/trade.controller.js";
import { addTradingCriterion, addTradingPair, addTradingStep, createTradingSystem, fetchTradingSystem, removeTradingCriterion, removeTradingPair, removeTradingStep, updateTradingCriteria, updateTradingPairs, updateTradingSteps, updateTradingSystem, } from "../controllers/trading/system.controller.js";
import { fetchTradingEquity, updateTradingAccountEquityMonth, updateTradingEquity, } from "../controllers/trading/equity.controller.js";
import { fetchTradeLevel, increaseXp, } from "../controllers/trading/xp_level.controller.js";
const router = Router();
router.post("/add-account", requireAuth, addNewAccount);
router.get("/fetch-accounts", requireAuth, fetchAccounts);
router.post("/add-trade", requireAuth, addNewTrade);
router.get("/fetch-trades", requireAuth, fetchTrades);
router.patch("/close-trade", requireAuth, closeTrade);
router.get("/system/fetch-system", requireAuth, fetchTradingSystem);
router.post("/system/create-system", requireAuth, createTradingSystem);
router.patch("/system/update-system", requireAuth, updateTradingSystem);
router.patch("/system/add-pair", requireAuth, addTradingPair);
router.patch("/system/remove-pair", requireAuth, removeTradingPair);
router.patch("/system/update-pairs", requireAuth, updateTradingPairs);
router.patch("/system/add-step", requireAuth, addTradingStep);
router.patch("/system/remove-step", requireAuth, removeTradingStep);
router.patch("/system/update-steps", requireAuth, updateTradingSteps);
router.patch("/system/add-criterion", requireAuth, addTradingCriterion);
router.patch("/system/remove-criterion", requireAuth, removeTradingCriterion);
router.patch("/system/update-criteria", requireAuth, updateTradingCriteria);
router.get("/fetch-trading-equity", requireAuth, fetchTradingEquity);
router.post("/update-trading-equity", requireAuth, updateTradingEquity);
router.patch("/update-trading-account-equity-month", requireAuth, updateTradingAccountEquityMonth);
router.get("/fetch-trade-level", requireAuth, fetchTradeLevel);
router.post("/increase-xp", requireAuth, increaseXp);
export default router;
//# sourceMappingURL=trading.route.js.map