import { SetupCriteria, TradeFormData } from "@/lib/types";
const sharedImg = "https://www.tradingview.com/x/OFAwlIUP/";

const criteriaAPlus: SetupCriteria = {
  isRefined: true,
  isBelowOrAboveOpeningPrice: true,
  isMssOccured: true,
  isIFVG: true,
  isFVG: true,
  isDisplacement: true,
  isLiquiditySweep: true,
  isPoiMitigated: true,
};

const criteriaA: SetupCriteria = {
  isRefined: true,
  isBelowOrAboveOpeningPrice: true,
  isMssOccured: true,
  isIFVG: true,
  isFVG: false,
  isDisplacement: true,
  isLiquiditySweep: true,
  isPoiMitigated: true,
};
export const demoClosedTrades: (TradeFormData & { id: string })[] = [
  {
    id: "csv-1856045059",
    pair: "AUDUSD",
    type: "Short",
    openTime: "2025-11-24T13:01:19",
    closeTime: "2025-11-24T20:37:26",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -2.82,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1858774299",
    pair: "AUDUSD",
    type: "Short",
    openTime: "2025-11-25T12:42:31",
    closeTime: "2025-11-25T13:10:24",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -2.34,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1863491129",
    pair: "EURUSD",
    type: "Long",
    openTime: "2025-11-27T11:15:33",
    closeTime: "2025-11-28T02:47:51",
    risk: 1,
    notes:
      "Price swept lows and showed a short-term bullish shift from discount. I used the fair value gap for entry, expecting continuation back above the opening price.",
    postNotes:
      "The move failed to develop after entry. Loss taken cleanly without adding or moving stop.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.05,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1867279628",
    pair: "EURUSD",
    type: "Long",
    openTime: "2025-12-01T01:03:37",
    closeTime: "2025-12-01T01:11:12",
    risk: 1,
    notes:
      "Trend is bullish and price traded below the opening price into sell-side liquidity. After bullish displacement left a fair value gap, I waited for retracement and entered from discount.",
    postNotes:
      "Clean continuation after entry. Displacement held and price respected the imbalance well into target.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.98,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1871660333",
    pair: "AUDUSD",
    type: "Short",
    openTime: "2025-12-02T11:17:13",
    closeTime: "2025-12-02T13:01:09",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -7.2,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1877456838",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2025-12-04T15:11:05",
    closeTime: "2025-12-04T15:19:06",
    risk: 1,
    notes:
      "Price traded into premium and swept buy-side liquidity before shifting structure. I used the first fair value gap retrace for a short entry.",
    postNotes:
      "The setup invalidated quickly. No adjustment, just a clean full-stop loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -1.48,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1880284770",
    pair: "",
    type: "Short",
    openTime: "2025-12-06T08:55:03",
    closeTime: "2025-12-06T08:55:32",
    risk: 1,
    notes:
      "There is a higher timeframe point of interest and price traded above the opening price into premium. After bearish displacement left a fair value gap, I entered on the retracement.",
    postNotes:
      "Very clean short. Premium array held, displacement was strong, and price moved smoothly into target.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.07,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1882321548",
    pair: "AUDUSD",
    type: "Long",
    openTime: "2025-12-08T13:38:01",
    closeTime: "2025-12-08T14:46:10",
    risk: 1,
    notes:
      "Bias is bullish and price traded below the opening price into a discount POI. Structure looked ready to shift, so I entered on the first imbalance retrace.",
    postNotes:
      "The setup had the right ingredients but there was no sustained follow through. Closed at planned loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -6.29,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1887981741",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2025-12-11T02:14:59",
    closeTime: "2025-12-11T02:31:51",
    risk: 1,
    notes:
      "Price traded into premium and swept buy-side liquidity before shifting structure. I used the first fair value gap retrace for a short entry.",
    postNotes:
      "The setup invalidated quickly. No adjustment, just a clean full-stop loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: 0,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1891444885",
    pair: "EURUSD",
    type: "Short",
    openTime: "2025-12-12T13:07:22",
    closeTime: "2025-12-12T14:51:36",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -6.4,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1893303156",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2025-12-15T01:46:36",
    closeTime: "2025-12-15T03:51:15",
    risk: 1,
    notes:
      "Previous day high was taken and price failed to hold above the opening price. Bearish orderblock mitigation and fair value gap gave the short entry.",
    postNotes:
      "Good confirmation and no major drawdown after entry. Market respected the bearish structure the whole way down.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.9,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1894660289",
    pair: "EURUSD",
    type: "Long",
    openTime: "2025-12-15T14:21:04",
    closeTime: "2025-12-15T14:59:36",
    risk: 1,
    notes:
      "Price delivered into discount after taking sell-side liquidity. Bullish orderflow returned with displacement, so I used the first FVG retrace for entry.",
    postNotes:
      "Strong follow through after mitigation. Entry was aligned and target was reached cleanly.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 24.7,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1896170825",
    pair: "AUDUSD",
    type: "Long",
    openTime: "2025-12-16T09:17:59",
    closeTime: "2025-12-16T13:31:20",
    risk: 1,
    notes:
      "Trend is bullish and price traded below the opening price into sell-side liquidity. After bullish displacement left a fair value gap, I waited for retracement and entered from discount.",
    postNotes:
      "Clean continuation after entry. Displacement held and price respected the imbalance well into target.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 25.32,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1901468008",
    pair: "EURUSD",
    type: "Long",
    openTime: "2025-12-18T15:17:59",
    closeTime: "2025-12-18T17:17:14",
    risk: 1,
    notes:
      "Bias is bullish and price traded below the opening price into a discount POI. Structure looked ready to shift, so I entered on the first imbalance retrace.",
    postNotes:
      "The setup had the right ingredients but there was no sustained follow through. Closed at planned loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -5.9,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1901973173",
    pair: "EURUSD",
    type: "Long",
    openTime: "2025-12-18T16:31:29",
    closeTime: "2025-12-18T17:17:14",
    risk: 1,
    notes:
      "Price swept lows and showed a short-term bullish shift from discount. I used the fair value gap for entry, expecting continuation back above the opening price.",
    postNotes:
      "The move failed to develop after entry. Loss taken cleanly without adding or moving stop.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -4.1,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1904399125",
    pair: "",
    type: "Short",
    openTime: "2025-12-20T14:32:28",
    closeTime: "2025-12-20T14:33:24",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.11,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1906495036",
    pair: "",
    type: "Long",
    openTime: "2025-12-22T14:55:46",
    closeTime: "2025-12-22T15:06:28",
    risk: 1,
    notes:
      "Bias is bullish and price traded below the opening price into a discount POI. Structure looked ready to shift, so I entered on the first imbalance retrace.",
    postNotes:
      "The setup had the right ingredients but there was no sustained follow through. Closed at planned loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.79,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1910693850",
    pair: "GBPUSD",
    type: "Long",
    openTime: "2025-12-24T12:33:43",
    closeTime: "2025-12-24T12:57:12",
    risk: 1,
    notes:
      "Price swept lows and showed a short-term bullish shift from discount. I used the fair value gap for entry, expecting continuation back above the opening price.",
    postNotes:
      "The move failed to develop after entry. Loss taken cleanly without adding or moving stop.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -10.8,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1914271534",
    pair: "",
    type: "Short",
    openTime: "2025-12-27T01:08:41",
    closeTime: "2025-12-27T01:10:40",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.14,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1915473930",
    pair: "EURUSD",
    type: "Short",
    openTime: "2025-12-29T07:34:43",
    closeTime: "2025-12-29T08:50:33",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -5.0,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1921418914",
    pair: "EURUSD",
    type: "Short",
    openTime: "2025-12-31T15:57:35",
    closeTime: "2025-12-31T20:38:44",
    risk: 1,
    notes:
      "Price traded into premium and swept buy-side liquidity before shifting structure. I used the first fair value gap retrace for a short entry.",
    postNotes:
      "The setup invalidated quickly. No adjustment, just a clean full-stop loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -4.88,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1921548650",
    pair: "EURUSD",
    type: "Short",
    openTime: "2025-12-31T17:51:00",
    closeTime: "2025-12-31T20:31:49",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -4.8,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1922703867",
    pair: "EURUSD",
    type: "Short",
    openTime: "2026-01-02T07:57:07",
    closeTime: "2026-01-02T10:08:24",
    risk: 1,
    notes:
      "Previous day high was taken and price failed to hold above the opening price. Bearish orderblock mitigation and fair value gap gave the short entry.",
    postNotes:
      "Good confirmation and no major drawdown after entry. Market respected the bearish structure the whole way down.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 24.44,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1922737412",
    pair: "EURUSD",
    type: "Short",
    openTime: "2026-01-02T08:11:12",
    closeTime: "2026-01-02T08:17:59",
    risk: 1,
    notes:
      "Bias is bearish and price retraced into premium before sweeping buy-side liquidity. Displacement occurred after the sweep, leaving an imbalance for the entry.",
    postNotes:
      "The setup delivered as expected. Entry location was good and the downside expanded nicely.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 5.49,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1924396228",
    pair: "",
    type: "Short",
    openTime: "2026-01-04T05:00:04",
    closeTime: "2026-01-04T05:30:33",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.5,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1925634178",
    pair: "EURUSD",
    type: "Short",
    openTime: "2026-01-05T09:23:45",
    closeTime: "2026-01-05T15:02:31",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -9.86,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1925699294",
    pair: "EURUSD",
    type: "Short",
    openTime: "2026-01-05T09:56:48",
    closeTime: "2026-01-05T10:19:35",
    risk: 1,
    notes:
      "Price traded into premium and swept buy-side liquidity before shifting structure. I used the first fair value gap retrace for a short entry.",
    postNotes:
      "The setup invalidated quickly. No adjustment, just a clean full-stop loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -6.7,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1930427013",
    pair: "EURUSD",
    type: "Short",
    openTime: "2026-01-07T12:37:39",
    closeTime: "2026-01-07T13:41:46",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -14.06,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1932325484",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2026-01-08T11:03:49",
    closeTime: "2026-01-09T08:46:16",
    risk: 1,
    notes:
      "Previous day high was taken and price failed to hold above the opening price. Bearish orderblock mitigation and fair value gap gave the short entry.",
    postNotes:
      "Good confirmation and no major drawdown after entry. Market respected the bearish structure the whole way down.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3.5,
    pnl_in_usd: 42.24,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1935617330",
    pair: "",
    type: "Short",
    openTime: "2026-01-11T03:03:44",
    closeTime: "2026-01-11T03:05:38",
    risk: 1,
    notes:
      "Bias is bearish and price retraced into premium before sweeping buy-side liquidity. Displacement occurred after the sweep, leaving an imbalance for the entry.",
    postNotes:
      "The setup delivered as expected. Entry location was good and the downside expanded nicely.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.18,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1938597105",
    pair: "",
    type: "Short",
    openTime: "2026-01-13T03:46:53",
    closeTime: "2026-01-13T03:47:23",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.19,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1947529783",
    pair: "",
    type: "Long",
    openTime: "2026-01-16T17:41:14",
    closeTime: "2026-01-16T17:42:24",
    risk: 1,
    notes:
      "Bias is bullish and there was a higher timeframe point of interest in discount. Price swept lows, shifted structure, and the fair value gap gave the long entry.",
    postNotes:
      "Model played out well. Good reaction from discount and no reason to cut the trade early.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.24,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1947835747",
    pair: "",
    type: "Short",
    openTime: "2026-01-18T05:24:58",
    closeTime: "2026-01-18T05:25:57",
    risk: 1,
    notes:
      "Price traded into premium and swept buy-side liquidity before shifting structure. I used the first fair value gap retrace for a short entry.",
    postNotes:
      "The setup invalidated quickly. No adjustment, just a clean full-stop loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.01,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1947303987",
    pair: "EURUSD",
    type: "Short",
    openTime: "2026-01-18T23:09:29",
    closeTime: "2026-01-18T23:43:28",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -14.85,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1954274462",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2026-01-21T13:48:50",
    closeTime: "2026-01-21T14:39:23",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -14.5,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1960040774",
    pair: "",
    type: "Long",
    openTime: "2026-01-23T13:05:07",
    closeTime: "2026-01-23T13:05:43",
    risk: 1,
    notes:
      "Price swept lows and showed a short-term bullish shift from discount. I used the fair value gap for entry, expecting continuation back above the opening price.",
    postNotes:
      "The move failed to develop after entry. Loss taken cleanly without adding or moving stop.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.19,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1963068737",
    pair: "EURUSD",
    type: "Long",
    openTime: "2026-01-26T10:09:47",
    closeTime: "2026-01-26T12:53:51",
    risk: 1,
    notes:
      "Trend is bullish but price only briefly reacted from discount after taking sell-side liquidity. There was displacement and a fair value gap, so I still took the long based on the model.",
    postNotes:
      "The idea did not continue after entry. Stop was respected for a full -1R and there was no reason to interfere with the plan.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -10.38,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1969857660",
    pair: "GBPUSD",
    type: "Long",
    openTime: "2026-01-28T14:39:51",
    closeTime: "2026-01-28T15:00:15",
    risk: 1,
    notes:
      "Bias is bullish and price traded below the opening price into a discount POI. Structure looked ready to shift, so I entered on the first imbalance retrace.",
    postNotes:
      "The setup had the right ingredients but there was no sustained follow through. Closed at planned loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -1.92,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1970135575",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2026-01-28T15:02:14",
    closeTime: "2026-01-28T23:36:01",
    risk: 1,
    notes:
      "Price traded into premium and swept buy-side liquidity before shifting structure. I used the first fair value gap retrace for a short entry.",
    postNotes:
      "The setup invalidated quickly. No adjustment, just a clean full-stop loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -8.82,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1970257461",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2026-01-28T15:55:29",
    closeTime: "2026-01-28T20:41:34",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -4.1,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1978520814",
    pair: "",
    type: "Short",
    openTime: "2026-01-31T16:35:01",
    closeTime: "2026-01-31T16:35:07",
    risk: 1,
    notes:
      "Previous day high was taken and price failed to hold above the opening price. Bearish orderblock mitigation and fair value gap gave the short entry.",
    postNotes:
      "Good confirmation and no major drawdown after entry. Market respected the bearish structure the whole way down.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.38,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1982147781",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2026-02-02T15:11:36",
    closeTime: "2026-02-03T00:24:18",
    risk: 1,
    notes:
      "Price traded into premium and swept buy-side liquidity before shifting structure. I used the first fair value gap retrace for a short entry.",
    postNotes:
      "The setup invalidated quickly. No adjustment, just a clean full-stop loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -10.26,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1985057066",
    pair: "AUDUSD",
    type: "Long",
    openTime: "2026-02-03T13:21:19",
    closeTime: "2026-02-03T14:07:12",
    risk: 1,
    notes:
      "Trend is bullish but price only briefly reacted from discount after taking sell-side liquidity. There was displacement and a fair value gap, so I still took the long based on the model.",
    postNotes:
      "The idea did not continue after entry. Stop was respected for a full -1R and there was no reason to interfere with the plan.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -8.28,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-1987408951",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2026-02-04T12:28:59",
    closeTime: "2026-02-04T15:31:26",
    risk: 1,
    notes:
      "Previous day high was taken and price failed to hold above the opening price. Bearish orderblock mitigation and fair value gap gave the short entry.",
    postNotes:
      "Good confirmation and no major drawdown after entry. Market respected the bearish structure the whole way down.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3.5,
    pnl_in_usd: 40.05,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1987837545",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2026-02-04T13:46:55",
    closeTime: "2026-02-04T15:31:26",
    risk: 1,
    notes:
      "Bias is bearish and price retraced into premium before sweeping buy-side liquidity. Displacement occurred after the sweep, leaving an imbalance for the entry.",
    postNotes:
      "The setup delivered as expected. Entry location was good and the downside expanded nicely.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 25.44,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1990917578",
    pair: "AUDUSD",
    type: "Short",
    openTime: "2026-02-05T16:30:02",
    closeTime: "2026-02-06T00:05:30",
    risk: 1,
    notes:
      "There is a higher timeframe point of interest and price traded above the opening price into premium. After bearish displacement left a fair value gap, I entered on the retracement.",
    postNotes:
      "Very clean short. Premium array held, displacement was strong, and price moved smoothly into target.",
    tierSetup: "A++",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 4,
    pnl_in_usd: 71.28,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1994350151",
    pair: "",
    type: "Long",
    openTime: "2026-02-08T04:54:12",
    closeTime: "2026-02-08T04:56:14",
    risk: 1,
    notes:
      "Bias is bullish and there was a higher timeframe point of interest in discount. Price swept lows, shifted structure, and the fair value gap gave the long entry.",
    postNotes:
      "Model played out well. Good reaction from discount and no reason to cut the trade early.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.16,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-1998924044",
    pair: "EURUSD",
    type: "Long",
    openTime: "2026-02-10T16:16:24",
    closeTime: "2026-02-10T17:04:44",
    risk: 1,
    notes:
      "Price swept lows and showed a short-term bullish shift from discount. I used the fair value gap for entry, expecting continuation back above the opening price.",
    postNotes:
      "The move failed to develop after entry. Loss taken cleanly without adding or moving stop.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -15.81,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2005296089",
    pair: "",
    type: "Long",
    openTime: "2026-02-13T13:24:26",
    closeTime: "2026-02-13T13:25:20",
    risk: 1,
    notes:
      "Trend is bullish and price traded below the opening price into sell-side liquidity. After bullish displacement left a fair value gap, I waited for retracement and entered from discount.",
    postNotes:
      "Clean continuation after entry. Displacement held and price respected the imbalance well into target.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 1.08,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-2006563795",
    pair: "",
    type: "Long",
    openTime: "2026-02-15T14:44:41",
    closeTime: "2026-02-15T14:51:20",
    risk: 1,
    notes:
      "Bias is bullish and price traded below the opening price into a discount POI. Structure looked ready to shift, so I entered on the first imbalance retrace.",
    postNotes:
      "The setup had the right ingredients but there was no sustained follow through. Closed at planned loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.83,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2007461670",
    pair: "AUDUSD",
    type: "Short",
    openTime: "2026-02-16T07:44:39",
    closeTime: "2026-02-16T08:05:19",
    risk: 1,
    notes:
      "Price traded into premium and swept buy-side liquidity before shifting structure. I used the first fair value gap retrace for a short entry.",
    postNotes:
      "The setup invalidated quickly. No adjustment, just a clean full-stop loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -22.88,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2011513701",
    pair: "AUDUSD",
    type: "Long",
    openTime: "2026-02-18T11:56:09",
    closeTime: "2026-02-18T13:44:44",
    risk: 1,
    notes:
      "Trend is bullish but price only briefly reacted from discount after taking sell-side liquidity. There was displacement and a fair value gap, so I still took the long based on the model.",
    postNotes:
      "The idea did not continue after entry. Stop was respected for a full -1R and there was no reason to interfere with the plan.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -18.09,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2016036873",
    pair: "",
    type: "Short",
    openTime: "2026-02-20T21:45:51",
    closeTime: "2026-02-20T21:45:58",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.06,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2017731862",
    pair: "AUDUSD",
    type: "Short",
    openTime: "2026-02-23T14:30:29",
    closeTime: "2026-02-24T12:20:24",
    risk: 1,
    notes:
      "Bias is bearish and price retraced into premium before sweeping buy-side liquidity. Displacement occurred after the sweep, leaving an imbalance for the entry.",
    postNotes:
      "The setup delivered as expected. Entry location was good and the downside expanded nicely.",
    tierSetup: "A++",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 4,
    pnl_in_usd: 61.92,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-2021366434",
    pair: "GBPUSD",
    type: "Long",
    openTime: "2026-02-25T14:10:16",
    closeTime: "2026-02-26T09:13:17",
    risk: 1,
    notes:
      "Trend is bullish and price traded below the opening price into sell-side liquidity. After bullish displacement left a fair value gap, I waited for retracement and entered from discount.",
    postNotes:
      "Clean continuation after entry. Displacement held and price respected the imbalance well into target.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 22.1,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-2025828389",
    pair: "",
    type: "Short",
    openTime: "2026-03-01T02:48:24",
    closeTime: "2026-03-01T02:48:28",
    risk: 1,
    notes:
      "Previous day high was taken and price failed to hold above the opening price. Bearish orderblock mitigation and fair value gap gave the short entry.",
    postNotes:
      "Good confirmation and no major drawdown after entry. Market respected the bearish structure the whole way down.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.1,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-2030997446",
    pair: "",
    type: "Long",
    openTime: "2026-03-04T01:35:38",
    closeTime: "2026-03-04T01:36:11",
    risk: 1,
    notes:
      "Price delivered into discount after taking sell-side liquidity. Bullish orderflow returned with displacement, so I used the first FVG retrace for entry.",
    postNotes:
      "Strong follow through after mitigation. Entry was aligned and target was reached cleanly.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.18,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-2032295553",
    pair: "",
    type: "Short",
    openTime: "2026-03-04T16:21:44",
    closeTime: "2026-03-05T03:21:07",
    risk: 1,
    notes:
      "Bias is bearish and price retraced above the opening price into premium. After a liquidity sweep and bearish displacement, I sold the fair value gap retracement.",
    postNotes:
      "Market did not continue after entry. Setup failed cleanly and the stop was respected for -1R.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -25.0,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2033691773",
    pair: "EURUSD",
    type: "Short",
    openTime: "2026-03-05T14:05:15",
    closeTime: "2026-03-05T20:15:16",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: 0,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2034118137",
    pair: "EURUSD",
    type: "Short",
    openTime: "2026-03-05T17:40:00",
    closeTime: "2026-03-05T20:15:16",
    risk: 1,
    notes:
      "Price traded into premium and swept buy-side liquidity before shifting structure. I used the first fair value gap retrace for a short entry.",
    postNotes:
      "The setup invalidated quickly. No adjustment, just a clean full-stop loss.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -11.06,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2036400536",
    pair: "",
    type: "Long",
    openTime: "2026-03-08T02:06:08",
    closeTime: "2026-03-08T02:06:16",
    risk: 1,
    notes:
      "Trend is bullish and price traded below the opening price into sell-side liquidity. After bullish displacement left a fair value gap, I waited for retracement and entered from discount.",
    postNotes:
      "Clean continuation after entry. Displacement held and price respected the imbalance well into target.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.1,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-2037613079",
    pair: "AUDUSD",
    type: "Short",
    openTime: "2026-03-09T09:12:07",
    closeTime: "2026-03-09T09:32:37",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -23.7,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2043244477",
    pair: "",
    type: "Long",
    openTime: "2026-03-12T11:53:42",
    closeTime: "2026-03-12T11:53:49",
    risk: 1,
    notes:
      "Price swept lows and showed a short-term bullish shift from discount. I used the fair value gap for entry, expecting continuation back above the opening price.",
    postNotes:
      "The move failed to develop after entry. Loss taken cleanly without adding or moving stop.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.26,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2043412572",
    pair: "GBPUSD",
    type: "Short",
    openTime: "2026-03-12T13:24:59",
    closeTime: "2026-03-13T07:00:16",
    risk: 1,
    notes:
      "There is a higher timeframe point of interest and price traded above the opening price into premium. After bearish displacement left a fair value gap, I entered on the retracement.",
    postNotes:
      "Very clean short. Premium array held, displacement was strong, and price moved smoothly into target.",
    tierSetup: "A++",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 4,
    pnl_in_usd: 61.38,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-2047484439",
    pair: "",
    type: "Short",
    openTime: "2026-03-16T12:12:00",
    closeTime: "2026-03-16T12:12:11",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -0.01,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
  {
    id: "csv-2049260817",
    pair: "GBPUSD",
    type: "Long",
    openTime: "2026-03-17T12:29:02",
    closeTime: "2026-03-18T05:11:20",
    risk: 1,
    notes:
      "Price delivered into discount after taking sell-side liquidity. Bullish orderflow returned with displacement, so I used the first FVG retrace for entry.",
    postNotes:
      "Strong follow through after mitigation. Entry was aligned and target was reached cleanly.",
    tierSetup: "A++",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 4,
    pnl_in_usd: 91.6,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-2056619880",
    pair: "",
    type: "Short",
    openTime: "2026-03-21T05:47:29",
    closeTime: "2026-03-21T05:47:55",
    risk: 1,
    notes:
      "There is a higher timeframe point of interest and price traded above the opening price into premium. After bearish displacement left a fair value gap, I entered on the retracement.",
    postNotes:
      "Very clean short. Premium array held, displacement was strong, and price moved smoothly into target.",
    tierSetup: "A+",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: 3,
    pnl_in_usd: 0.14,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaAPlus,
  },
  {
    id: "csv-2061039738",
    pair: "AUDUSD",
    type: "Short",
    openTime: "2026-03-24T11:40:34",
    closeTime: "2026-03-24T20:22:44",
    risk: 1,
    notes:
      "Previous day high was taken and price looked ready to reject from premium. Bearish orderblock mitigation plus imbalance gave the short entry.",
    postNotes:
      "The idea was valid but there was no real expansion after entry. Accepted the full loss and moved on.",
    tierSetup: "A",
    preSetupImg: [sharedImg],
    postSetupImg: sharedImg,
    pnl: -1,
    pnl_in_usd: -25.35,
    accounts: ["m4cren", "funded_m4cren"],
    setupCriteria: criteriaA,
  },
];
